name: skeleton
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  slang: ^4.11.1
  slang_flutter: ^4.11.0
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  flutter_hooks: ^0.21.3+1
  auto_route: ^11.0.0
  intl: ^0.20.2
  rxdart: ^0.28.0
  logger: ^2.6.2
  gap: ^3.0.1
  forui: ^0.16.0
  forui_hooks: ^0.16.0
  json_annotation: ^4.9.0
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.4.0
  json_serializable: ^6.11.2
  build_runner: ^2.10.4
  freezed: ^3.2.3
  very_good_analysis: ^10.0.0
  injectable_generator: ^2.9.1
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/
